name: Deploy

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  publish-whl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: pip install build twine

      - name: Set unique version
        run: |
          NEW_VERSION="0.1.${{ github.run_number }}"
          sed -i "s/^version = \".*\"/version = \"$NEW_VERSION\"/" pyproject.toml
          echo "Building version $NEW_VERSION"
          grep "^version" pyproject.toml

      - name: Build wheel
        run: python -m build --wheel

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/663118040756/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          service_account: 'gha-artifact-publisher@project-5052331c-acde-45d8-b54.iam.gserviceaccount.com'

      - uses: google-github-actions/setup-gcloud@v2

      - name: Get access token
        run: echo "TOKEN=$(gcloud auth print-access-token)" >> $GITHUB_ENV

      - name: Publish to Artifact Registry
        run: |
          python -m twine upload --skip-existing \
            --repository-url https://asia-south1-python.pkg.dev/project-5052331c-acde-45d8-b54/udp-python/ \
            -u oauth2accesstoken -p "$TOKEN" \
            dist/*.whl