name: Deploy Python Wheel

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  publish-whl:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout source
        uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      # Install build dependencies
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine keyring keyrings.google-artifactregistry-auth

      # Generate a unique package version
      - name: Set unique version
        run: |
          NEW_VERSION="0.1.${{ github.run_number }}"
          sed -i "s/^version = \".*\"/version = \"$NEW_VERSION\"/" pyproject.toml

          echo "Building version: $NEW_VERSION"
          grep "^version" pyproject.toml

      # Build wheel
      - name: Build wheel
        run: python -m build --wheel

      # Verify generated wheel
      - name: Verify package
        run: |
          ls -lh dist/
          python -m twine check dist/*

      # Authenticate using Workload Identity Federation
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/663118040756/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider"
          service_account: "gha-artifact-publisher@project-5052331c-acde-45d8-b54.iam.gserviceaccount.com"

      # Install gcloud CLI
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      # Publish the wheel
      - name: Publish to Artifact Registry
        run: |
          TOKEN=$(gcloud auth print-access-token)

          python -m twine upload \
            --repository-url https://asia-south1-python.pkg.dev/project-5052331c-acde-45d8-b54/udp-python/ \
            -u oauth2accesstoken \
            -p "$TOKEN" \
            dist/*.whl